### PR TITLE
Add a tooltip for execute command arguments

### PR DESCRIPTION
**Pull request by doronbehar**
NOTE: Haven't tested this...

### CODE REVIEW

**Comment by ghost** [comment]
I have already added a tooltip to  the settings dialog yesterday (https://github.com/AyatanaIndicators/ayatana-webmail/commit/457f1e15e5185f8229c8987e4ce4003e732e8647).  :)

**Comment by ghost** [comment]
@doronbehar: Can we close this pull request in favour of https://github.com/AyatanaIndicators/ayatana-webmail/commit/457f1e15e5185f8229c8987e4ce4003e732e8647?

**Comment by doronbehar** [comment]
Yes.

**Comment by ghost** [comment]
Closing as already fixed by https://github.com/AyatanaIndicators/ayatana-webmail/commit/457f1e15e5185f8229c8987e4ce4003e732e8647

**Pull request closed without merging**
